# Generated by Django 5.1.2 on 2024-10-11 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='videos.video', verbose_name='video'),
        ),
    ]
